/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Expense = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'paymentMode' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Settings = IDL.Record({
  'pin' : IDL.Text,
  'monthlyBudget' : IDL.Float64,
  'annualIncome' : IDL.Float64,
  'darkMode' : IDL.Bool,
  'pinEnabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func([Expense], [], []),
  'deleteExpense' : IDL.Func([IDL.Text], [], []),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getExpensesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'updateExpense' : IDL.Func([Expense], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'paymentMode' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Settings = IDL.Record({
    'pin' : IDL.Text,
    'monthlyBudget' : IDL.Float64,
    'annualIncome' : IDL.Float64,
    'darkMode' : IDL.Bool,
    'pinEnabled' : IDL.Bool,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func([Expense], [], []),
    'deleteExpense' : IDL.Func([IDL.Text], [], []),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getExpensesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'updateExpense' : IDL.Func([Expense], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };