/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expense {
  'id' : string,
  'date' : string,
  'createdAt' : bigint,
  'notes' : string,
  'paymentMode' : string,
  'category' : string,
  'amount' : number,
}
export interface Settings {
  'pin' : string,
  'monthlyBudget' : number,
  'annualIncome' : number,
  'darkMode' : boolean,
  'pinEnabled' : boolean,
}
export interface _SERVICE {
  'addExpense' : ActorMethod<[Expense], undefined>,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getExpensesByCategory' : ActorMethod<[string], Array<Expense>>,
  'getSettings' : ActorMethod<[], Settings>,
  'updateExpense' : ActorMethod<[Expense], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];